version: '3'
services:
  filebeat:
    image: olinicola/filebeat:1.2.3
    env_file:
      - filebeat_variables.env
    volumes:
      - ${FILEBITE_NGINX_DIR}:/etc/logs/nginx # nginx logs
      - ${FILEBITE_BASE_DIR}:/etc/filebeat
      - ${FILEBITE_TMP_DIR}:/tmp/filebeat
      - ${FILEBITE_CERTS_DIR}:/etc/pki/tls/certs
    links:
      - "logstash"
    depends_on:
      - "logstash"
    #entrypoint: ./time-to-start.sh

  elasticsearch:
    image: elasticsearch:5.6
    restart: always
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  logstash:
    build: logstash
    restart: always
    command: logstash -f /config-dir/logstash.conf
    ports:
      - 5044:5044
    links:
      - elasticsearch

  kibana:
    image: kibana:5
    restart: always
    ports:
      - 5601:5601
    links:
      - elasticsearch